name: build
on:
  - push
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build the ansible execution environment
        run: ./ansible-lint.sh --version
      - name: Lint the lab.yml playbook
        run: ./ansible-lint.sh --offline --parseable lab.yml
